[project]
name = "media-log"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["Django"]

[dependency-groups]
dev = [
    "debugpy>=1.8.14",
]
