# Generated by Django 5.1.7 on 2025-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_publish_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="nobel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="publish_year",
            field=models.IntegerField(null=True),
        ),
    ]
