# Generated by Django 5.1.7 on 2025-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_author_nobel_book_publish_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
