# Generated by Django 5.1.7 on 2025-03-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="prize",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="books.prize"
            ),
        ),
    ]
