# Generated by Django 5.1.7 on 2025-03-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_edition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="format",
            field=models.CharField(
                choices=[("P", "print"), ("D", "digital"), ("A", "audio")], max_length=1
            ),
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_started", models.DateField(null=True)),
                ("date_finished", models.DateField(null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("W", "want to read"),
                            ("R", "currently reading"),
                            ("F", "finished"),
                        ],
                        default="W",
                        max_length=1,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.edition"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("pages_read", models.IntegerField(blank=True, null=True)),
                ("percentage_complete", models.FloatField(blank=True, null=True)),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="books.reading",
                    ),
                ),
            ],
        ),
    ]
