# Generated by Django 5.1.7 on 2025-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_edition_format_reading_readinglog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="date_finished",
            field=models.DateField(blank=True, null=True),
        ),
    ]
