# Generated by Django 5.1.7 on 2025-03-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_alter_reading_date_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="edition",
            name="pages",
            field=models.IntegerField(null=True),
        ),
    ]
