# Generated by Django 5.1.7 on 2025-03-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_book_pages_edition_pages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="pages",
            new_name="page_count",
        ),
        migrations.RemoveField(
            model_name="edition",
            name="pages",
        ),
        migrations.AddField(
            model_name="edition",
            name="isbn",
            field=models.CharField(max_length=14, null=True),
        ),
    ]
