# Generated by Django 5.1.7 on 2025-03-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_book_series_order_series_book_series"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readinglog",
            options={"verbose_name_plural": "Reading Logs"},
        ),
        migrations.AlterField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.series",
            ),
        ),
    ]
