# Generated by Django 5.1.7 on 2025-03-07 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_alter_readinglog_options_alter_book_series"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prize",
            new_name="Award",
        ),
        migrations.CreateModel(
            name="BookAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("W", "won"), ("S", "shortlisted")], max_length=1
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "prize",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.award"
                    ),
                ),
            ],
            options={
                "unique_together": {("book", "prize", "year")},
            },
        ),
    ]
