# Generated by Django 5.1.7 on 2025-03-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_rename_prize_award_bookaward"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookaward",
            options={"verbose_name_plural": "Book Awards"},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name_plural": "Series"},
        ),
    ]
