# Generated by Django 5.1.7 on 2025-03-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_alter_bookaward_options_alter_series_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="prize",
        ),
        migrations.AddField(
            model_name="book",
            name="awards",
            field=models.ManyToManyField(
                blank=True, through="books.BookAward", to="books.award"
            ),
        ),
    ]
