# Generated by Django 5.1.7 on 2025-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_remove_book_prize_book_awards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="about",
            field=models.CharField(max_length=200),
        ),
    ]
