# Generated by Django 5.1.7 on 2025-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_alter_award_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="about",
            field=models.CharField(max_length=400),
        ),
    ]
