# Generated by Django 5.1.7 on 2025-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0019_alter_award_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="status",
            field=models.CharField(
                choices=[
                    ("W", "want to read"),
                    ("P", "in_progress"),
                    ("F", "finished"),
                ],
                default="W",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reading",
            name="current_status",
            field=models.CharField(
                choices=[("R", "currently reading"), ("F", "finished")],
                default="R",
                max_length=1,
            ),
        ),
    ]
