# Generated by Django 5.1.7 on 2025-03-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0020_edition_status_alter_reading_current_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="isbn",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="edition",
            name="publish_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
