# Generated by Django 5.1.7 on 2025-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0021_alter_edition_isbn_alter_edition_publish_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="status",
            field=models.CharField(
                choices=[
                    ("W", "want to read"),
                    ("P", "in progress"),
                    ("F", "finished"),
                ],
                default="W",
                max_length=1,
            ),
        ),
    ]
